---

- name: check sdr installed
  stat:
    path: /usr/local/bin/rtl_sdr
  register: sdr_binary

- name: install dependencies
  become: yes
  package:
    name: 
      - cmake
      - build-essential
      - python-pip
      - libusb-1.0-0-dev
      - python-numpy 
      - pandoc
    state: present
  when: not sdr_binary.stat.exists

- name: clone repo
  git:
    repo: git://git.osmocom.org/rtl-sdr.git
    dest: "{{ sdr_download_location }}"
  when: not sdr_binary.stat.exists

- name: build dir
  file: 
    path: "{{ sdr_download_location }}/build"
    state: directory
    mode: 0755
  when: not sdr_binary.stat.exists

- name: cmake
  command: 
    cmd: cmake ../
    chdir: "{{ sdr_download_location }}/build"
    creates: "{{ sdr_download_location }}/build/*.cmake"
  when: not sdr_binary.stat.exists
    
- name: make
  make: 
    chdir: "{{ sdr_download_location }}/build"
  when: not sdr_binary.stat.exists

- name: install
  make: 
    target: install
    chdir: "{{sdr_download_location}}/build"
  become: yes
  when: not sdr_binary.stat.exists

- name: ldconfig
  command: ldconfig
  become: yes
  when: not sdr_binary.stat.exists

