---

- name: blacklist dvb_usb_rtl28xxu
  shell: echo 'blacklist dvb_usb_rtl28xxu' | tee --append /etc/modprobe.d/blacklist-dvb_usb_rtl28xxu.conf
  become: yes

- name: copy service file
  copy:
    src: rtl433.service
    dest: /etc/systemd/system/rtl433.service
  become: yes

- name: copy rtl rules
  copy:
    src: rtl-sdr.rules
    dest: /etc/udev/rules.d/rtl-sdr.rules
  become: yes

- name: start rtl service
  systemd: 
    name: rtl433 
    state: started
    enabled: yes
    daemon_reload: yes
  become: yes

