---

- name: create logs directory
  file:
    path: /var/log/ha
    state: directory
    owner: pi
  become: yes

- name: set up logrotate
  template:
    src: logrotate.j2
    dest: /etc/logrotate.d/ha
    owner: root
    group: root
    mode: 0644
  become: yes
