---

- name: install packages
  become: yes
  package:
    name: 
      - msmtp 
      - msmtp-mta
    state: present
    update_cache: yes

- name: copy mail config
  template:
    src: templates/msmtprc
    dest: /etc/msmtprc
  become: yes
