---

- name: install dependencies
  become: yes
  package:
    name: 
      - apache2
      - php
      #- mariadb-server
      - php-mysql
      - python3-pymysql
    state: present

- name: install pymysql
  become: true
  pip:
    name: pymysql
    state: present