---

- name: "install cron task: temperature: {{ansible_hostname}}"
  cron:
    name: "temperature {{item}}"
    minute: "{{offset}}-59/{{upload.interval.min}}"
    job: "~/ha/upload/{{ansible_hostname}}/channel{{item}}.sh >>/var/log/ha/upload{{item}}.log 2>&1"
  loop: "{{channels}}"
         
  