---
#Install cron tasks

- hosts: pi2
  user: pi
  tasks:
    - name: Create a directory if it does not exist
      file:
        path: /var/log/ha
        state: directory
        owner: pi
      become: yes
    - name: "install cron task: relay up"
      cron:
        name: "relay up"
        hour: "7"
        minute: "00"
        job: "~/ha/relay/all/up.sh >>/var/log/ha/relay.out 2>>/var/log/ha/relay.err"
    - name: "install cron task: relay up"
      cron:
        name: "relay down"
        hour: "21"
        minute: "00"
        job: "~/ha/relay/all/down.sh >>/var/log/ha/relay.out 2>>/var/log/ha/relay.err"
    - name: "install cron task: temperature"
      cron:
        name: "temperature"
        minute: "*/5"
        job: "cd ~/home-automation/ && ./upload/channel3.sh >>/var/log/ha/upload3.log 2>>/var/log/ha/upload3.err"
         
    