---

- hosts: pi2
  user: pi
  pre_tasks:
    - name: include vault vars
      include_vars: "vault.yml"
      tags: ["always"]
  roles:
    # - load2db
    - charts
   
  #- common
  #- shutters
  #- role: upload
  #  vars: 
  #    channels: [3]
  
  
  