---

- hosts: pi2
  user: pi
  pre_tasks:
    - name: include vault vars
      include_vars: "vault.yml"
      tags: ["always"]
  roles:
    #- common
    #- load2db
    #- charts
    #- shutters
    - role: upload
      vars: 
        channels: [3,4]
        offset: 0

  
  
  